language: node_js

node_js:
  - 10
  - 12
  - 14
  - 16

os:
  - linux
  - osx
  - windows

cache: npm

install:
  - npm install

git:
  quiet: true
  depth: 1

script:
  - npm run build

jobs:
  include:
    - stage: Produce Coverage
      node_js: 14
      script: ./coveralls/.bin/jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
