name: NPM publish

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 16
      uses: actions/setup-node@master
      with:
        node-version: 16
        registry-url: https://registry.npmjs.org/
    - run: npm ci
    - run: npm run build
    - run: npm test
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
    - name: update version 
      run: |
        npm version patch
        git add package.json
        git commit -m "update version"
        git push
      env:
        github-token: ${{ secrets.github_token }}
